### ISSUE TITLE
Socket getting disconnected when an activity is paused.

### ISSUE THREAD

**Issue by djohn17** [comapi/comapi-sdk-android#13]
Hello team,

I am encountering a weird issue. I can open an activity containing a fragment that shows list of chat messages. I am successfully able to send text and images using COMAPI. But what I notice is everytime I try to add an image attachment by opening a new activity, the socket is internally getting disconnected due to which if anyone during this time tries to send any message to me, my app isn't able to handle those events. Socket disconnection is happening with the COMAPI library. Could you let me know your thoughts on this issue.

**Comment by MarcinSwierczek** [comment]
Hi @djohn17,

What’s happening is that going to pictures activity is effectively backgrounding the app which is by design switching the socket off. Way to synchronise the conversations after user goes back to chat activity is:

1. client.service().messaging().getConversations(false) will return list of conversations
2. each of them will contain latestSentEventId which needs to be compared with locally stored one
3. then for each conversation
eventIdToStartFrom = savedLatestSentEventId + 1
limitOfEventsToObtain - limit of events per one response e.g. 100
client.service().messaging().queryConversationEvents(conversationId, eventIdToStartFrom, limitOfEventsToObtain) will return batch of conversation events to process
Then repeat this call until you get number of events smaller than limitOfEventsToObtain - which will mean that you received all events in a conversation that were published after event with event id equal eventIdToStartFrom.

You can also wait a few days for a release of a new library that will wrap the Foundation SDK and will manage the conversations for you automatically. The new library is design to make the integration process much simpler when building a chat functionality with Comapi.

**Comment by djohn17** [comment]
When is the expected release date for this new library?

**Comment by MarcinSwierczek** [comment]
Should be available by the middle of next week. I will keep you posted.

**Comment by MarcinSwierczek** [comment]
Hi @djohn17,

The [Chat SDK](https://github.com/comapi/comapi-chat-sdk-android) is now available. You can find docs [here](https://docs.comapi.com/reference#android-chat) and sample apps [here](https://github.com/comapi/comapi-sdk-android-samples).

It will automatically 
- manage conversations
- manage socket reconnections
- synchronise conversation data when the app becomes foregrounded or socket reconnected.
- manage sending attachments with messages and update message data with urls for the uploaded  content
- timely update persistence store when sending messages and filter out duplicates
- mark messages as delivered
and also
- Replace message&events queries with simple paging API
